export const valueById = {
    "1": "Model X (High Performance)",
    "2": "Model Y (Versatile Design)",
    "3": "Model Z (All-Terrain Capability)",
    "4": "Model A1 (Beginner Friendly)",
    "5": "Model B1 (Intermediate Performance)",
    "6": "Model C1 (Advanced Technology)",
    "7": "Model D1 (Professional Grade)",
    "8": "Model E1 (Eco-Friendly Design)",
    "9": "Model F1 (Lightweight and Fast)",
    "10": "Model G1 (Durable and Reliable)",
    "11": "Model H1 (Comfort Focused)",
    "12": "Model I1 (Precision Engineering)",
    "13": "Model J1 (Customizable Features)",
    "14": "Model K1 (Classic Design)",
    "15": "Model L1 (Modern Aesthetics)",
    "16": "Model M1 (High-Tech Integration)",
    "17": "Model N1 (User-Friendly Interface)",
    "18": "Model O1 (Performance Optimized)",
    "19": "Model P1 (All-Around Performer)",
    "20": "Model Q1 (For Competitive Players)",
    "21": "Model R1 (For Casual Players)",
    "22": "Model S1 (For Family Use)",
    "23": "Model T1 (For Beginners)",
    "24": "Model U1 (For Professionals)",
    "25": "Model V1 (For Eco-Conscious Users)",
    "26": "Model W1 (For High Performance)",
    "27": "Model X1 (For Versatile Use)",
    "28": "Model Y1 (For Advanced Players)",
    "29": "Model Z1 (For All Conditions)",
    "30": "Model A2 (For Customization)",
    "31": "Model B2 (For Comfort)",
    "32": "Model C2 (For Speed)",
    "33": "Model D2 (For Stability)",
    "34": "Model E2 (For Control)",
    "35": "Model F2 (For Distance)",
    "36": "Model G2 (For Precision)"
};
